// Generated by CoffeeScript 1.8.0
(function () {
  this.Str = (function () {
    function Str () {}

    Str.decode = function (s) {
      return s
    }

    Str.ucfirst = function (str) {
      return str.substr(0, 1).toUpperCase() + str.substr(1)
    }

    Str.nl2br = function (str, is_xhtml) {
      var breakTag
      breakTag = is_xhtml || typeof is_xhtml === 'undefined' ? '<br ' + '/>' : '<br>'
      return (str + '').replace(/([^>\r\n]?)(\r\n|\n\r|\r|\n)/g, '$1' + breakTag + '$2')
    }

    return Str

  })()

}).call(this)

//# sourceMappingURL=Str.js.map
