// Generated by CoffeeScript 1.8.0
(function () {
  this.Validate = (function () {
    var commonCheck, isValid, removeError, showError

    function Validate () {}

    commonCheck = function (fields) {
      var fld, hasErrors, key, name, valid, _i, _len
      hasErrors = false
      for (key = _i = 0, _len = fields.length; _i < _len; key = ++_i) {
        fld = fields[key]
        name = $(fld).prop('name')
        valid = isValid(fld)
        if (!valid) {
          hasErrors = true
        }
      }
      return !hasErrors
    }

    Validate.Package = function (fields) {
      if (!commonCheck(fields)) {
        return false
      }
      return true
    }

    Validate.Greeting = function (fields) {
      if (!commonCheck(fields)) {
        return false
      }
      return true
    }

    Validate.Cart = function (fields) {
      if (!commonCheck(fields)) {
        return false
      }
      return true
    }

    Validate.Delivery = function (fields) {
      if (!commonCheck(fields)) {
        return false
      }
      return true
    }

    Validate.Login = function (fields) {
      if (!commonCheck(fields)) {
        return false
      }
      return true
    }

    Validate.Payment = function (fields) {
      if (!commonCheck(fields)) {
        return false
      }
      return true
    }

    isValid = function (fld) {
      var dataType, isRequired, maxlength, minlength, name, value
      fld = $(fld)
      name = fld.prop('name')
      value = fld.val()
      isRequired = fld.prop('required')
      minlength = parseInt(fld.attr('minlength'), 10)
      maxlength = parseInt(fld.attr('maxlength'), 10)
      if (isRequired && value.length === 0) {
        showError(fld)
        return false
      }
      if (minlength && value.length && value.length < minlength) {
        showError(fld)
        return false
      }
      if (maxlength && value.length && value.length > maxlength) {
        showError(fld)
        return false
      }
      dataType = fld.prop('data-type')
      removeError(fld)
      return true
    }

    showError = function (fld) {
      var cont, err
      err = fld.attr('data-error')
      if (!err) {
        err = 'Проверьте правильность заполнения'
      }
      cont = fld.parent()
      cont.find('.err').html(err).show()
      return cont.addClass('stop')
    }

    removeError = function (fld) {
      var cont
      cont = fld.parent()
      cont.find('.err').html('').hide()
      return cont.removeClass('stop')
    }

    return Validate

  })()

}).call(this)

//# sourceMappingURL=Validate.js.map
